# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  gcp-iasm-lab

stages:
  - stage: Attention_data
    jobs:
      - job: Attention_data
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Install dependencies'
        - script: |
            robot -x outputxunit.xml ./Attention_data.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Attention_data test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Attention_data_log'
          condition: succeededOrFailed()
          displayName: upload log

  - stage: Operations_Supervisor_data
    jobs:
      - job: Operations_Supervisor_data
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Install dependencies'
        - script: |
            robot -x outputxunit.xml ./Operations_Supervisor_data.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Operations_Supervisor_data test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Operations_Supervisor_data_log'
          condition: succeededOrFailed()
          displayName: upload log
  - stage: ISOAttention_data
    jobs:
      - job: ISOAttention_data
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            robot -x outputxunit.xml ./ISOAttention_data.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: ISOAttention_data test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'ISOAttention_data_log'
          condition: succeededOrFailed()
          displayName: upload log
  - stage: Unit_Head
    jobs:
      - job: Unit_Head
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            robot -x outputxunit.xml ./Unit_Head.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Unit_Head test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Unit_Head_log'
          condition: succeededOrFailed()
          displayName: upload log
  - stage: System_Admin
    jobs:
      - job: System_Admin
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            robot -x outputxunit.xml ./System_Admin.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: System_Admin test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'System_Admin_log'
          condition: succeededOrFailed()
          displayName: upload log


