# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  gcp-iasm-lab

stages:
  - stage: Land_Attention_data
    jobs:
      - job: Land_Attention_data
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Install dependencies'
        - script: |
            robot -x outputxunit.xml ./Land_Attention_data.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Land_Attention_data test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Land_Attention_data_log'
          condition: succeededOrFailed()
          displayName: upload log

  - stage: Land_Operations_Supervisor_data
    jobs:
      - job: Land_Operations_Supervisor_data
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Install dependencies'
        - script: |
            robot -x outputxunit.xml ./Land_Operations_Supervisor_data.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Land_Operations_Supervisor_data test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Land_Operations_Supervisor_data_log'
          condition: succeededOrFailed()
          displayName: upload log
  - stage: Land_ISOAttention_data
    jobs:
      - job: Land_ISOAttention_data
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            robot -x outputxunit.xml ./Land_ISOAttention_data.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Land_ISOAttention_data test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Land_ISOAttention_data_log'
          condition: succeededOrFailed()
          displayName: upload log
  - stage: Land_Unit_Head
    jobs:
      - job: Land_Unit_Head
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            robot -x outputxunit.xml ./Land_Unit_Head.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Land_Unit_Head test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Land_Unit_Head_log'
          condition: succeededOrFailed()
          displayName: upload log
  - stage: Land_System_Admin
    jobs:
      - job: Land_System_Admin
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            robot -x outputxunit.xml ./Land_System_Admin.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Land_System_Admin test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Land_System_Admin_log'
          condition: succeededOrFailed()
          displayName: upload log
  - stage: Cloud_Attention_data
    jobs:
      - job: Cloud_Attention_data
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Install dependencies'
        - script: |
            robot -x outputxunit.xml ./Cloud_Attention_data.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Cloud_Attention_data test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Cloud_Attention_data_log'
          condition: succeededOrFailed()
          displayName: upload log
  - stage: Cloud_Operations_Supervisor
    jobs:
      - job: Cloud_Operations_Supervisor
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Install dependencies'
        - script: |
            robot -x outputxunit.xml ./Cloud_Operations_Supervisor.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Cloud_Operations_Supervisor test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Cloud_Operations_Supervisor_log'
          condition: succeededOrFailed()
          displayName: upload log
  - stage: Cloud_Unit_Head
    jobs:
      - job: Cloud_Unit_Head
        timeoutInMinutes: 120
        continueOnError: true
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
        - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Install dependencies'
        - script: |
            robot -x outputxunit.xml ./Cloud_Unit_Head.robot
          displayName: 'Run Robot'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'outputxunit.xml'
            testRunTitle: Cloud_Unit_Head test
          condition: succeededOrFailed()
          displayName: 'Publish Test Results outputxunit.xml'
        - task: CmdLine@2
          inputs:
            script: |
              mkdir $(System.DefaultWorkingDirectory)/log
              cp ./*.png $(System.DefaultWorkingDirectory)/log
              cp ./*.html $(System.DefaultWorkingDirectory)/log
          condition: succeededOrFailed()
          displayName: 'Copy screenshot and html to folder'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/log'
            ArtifactName: 'Cloud_Unit_Head_log'
          condition: succeededOrFailed()
          displayName: upload log


